# Explore and Clean Flight Dataset

Data from: https://zenodo.org/record/4670228#.YIL5Y0UzaUk

In [113]:
import pandas as pd
import numpy as np

## Load Data

In [114]:
flights = pd.read_csv("flightlist_20190101_20190131.csv")
print(flights.shape)
flights.head(10)

E:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(2145469, 16)

,callsign,number,icao24,registration,typecode,origin,destination,firstseen,lastseen,day,latitude_1,longitude_1,altitude_1,latitude_2,longitude_2,altitude_2
0,HVN19,NaN,888152,NaN,NaN,YMML,LFPG,2018-12-31 00:43:16+00:00,2019-01-01 04:56:29+00:00,2019-01-01 00:00:00+00:00,-37.659485,144.804421,304.8,48.995316,2.610802,-53.34
1,CCA839,NaN,780ad1,NaN,NaN,YMML,LEBL,2018-12-31 00:53:08+00:00,2019-01-01 06:01:42+00:00,2019-01-01 00:00:00+00:00,-37.692123,144.841997,304.8,41.036124,2.063557,1112.52
2,CES219,NaN,780b7e,B-5936,A332,YSSY,EDDF,2018-12-31 01:05:29+00:00,2019-01-01 04:09:29+00:00,2019-01-01 00:00:00+00:00,-33.930908,151.171987,0.0,50.045563,8.588923,-15.24
3,AEA040,NaN,34444e,EC-LVL,A332,LEMD,LEMD,2018-12-31 01:07:21+00:00,2019-01-01 03:32:59+00:00,2019-01-01 00:00:00+00:00,40.534756,-3.575426,609.6,40.475728,-3.538347,411.48
4,CXA825,NaN,780d75,B-2760,B788,YSSY,LFPG,2018-12-31 01:18:29+00:00,2019-01-01 04:32:28+00:00,2019-01-01 00:00:00+00:00,-33.954254,151.178041,0.0,48.996091,2.625805,22.86
5,TGW700,NaN,76bcca,9V-OFJ,B788,NaN,RJBB,2018-12-31 01:30:50+00:00,2019-01-01 08:19:13+00:00,2019-01-01 00:00:00+00:00,34.641243,140.942345,8534.4,34.449354,135.237179,-99.06
6,CLU211,NaN,406ea3,G-CLAA,B744,UUEE,EDDF,2018-12-31 01:49:28+00:00,2019-01-01 04:11:38+00:00,2019-01-01 00:00:00+00:00,55.967560,37.371327,304.8,50.044400,8.583737,-30.48
7,CSN609,NaN,781364,NaN,NaN,NaN,KLAX,2018-12-31 02:28:27+00:00,2019-01-01 04:53:37+00:00,2019-01-01 00:00:00+00:00,37.042923,114.838685,10972.8,33.952057,-118.383627,129.54
8,CSN679,NaN,780db0,B-5967,A333,NaN,LTBA,2018-12-31 03:08:15+00:00,2019-01-01 02:09:11+00:00,2019-01-01 00:00:00+00:00,37.002884,114.842715,10972.8,40.804184,28.714478,2011.68
9,ETH704,NaN,04004b,ET-AOU,B788,KLDJ,LFPG,2018-12-31 03:31:48+00:00,2019-01-01 04:30:10+00:00,2019-01-01 00:00:00+00:00,40.584567,-74.228314,609.6,48.996002,2.623408,0.00

## Get Relevant Columns

In [109]:
flights.columns

Index(['callsign', 'number', 'icao24', 'registration', 'typecode', 'origin',
       'destination', 'firstseen', 'lastseen', 'day', 'latitude_1',
       'longitude_1', 'altitude_1', 'latitude_2', 'longitude_2', 'altitude_2'],
      dtype='object')

In [115]:
flights = flights[["day","origin", "destination"]]
flights = flights.dropna()
flights = flights.sample(1000, random_state = 10)
print(flights.shape)
flights.head()

(1000, 3)

                               day origin destination
1034920  2019-01-16 00:00:00+00:00   KEWR        KDFW
33654    2019-01-01 00:00:00+00:00   KONT        KPHX
584986   2019-01-09 00:00:00+00:00   LSZH        LTBA
963099   2019-01-15 00:00:00+00:00   KSFO        KSAN
6586     2019-01-01 00:00:00+00:00   PANC        MS65

In [116]:
unique = np.unique(np.append(flights["origin"], flights["destination"]))
print(unique.shape)
unique

(664,)

array(['01FA', '02XS', '06FA', '06TE', '0GA1', '0GA2', '0NY0', '0WI5',
       '13AZ', '14FA', '16FA', '16TX', '1AZ2', '1CO4', '1LA1', '1OR3',
       '1WI6', '1XS1', '20GA', '20II', '21XS', '27CA', '2AZ7', '2KS9',
       '2TS2', '32II', '35MN', '38MO', '3GE9', '3IN7', '3MD4', '3PS9',
       '44PA', '4FL8', '4NY4', '4TS8', '54MI', '57FA', '59TX', '5TA4',
       '60CO', '60IN', '60MI', '64NC', '6NJ9', '71MI', '72FL', '73WA',
       '77TS', '78MI', '79NY', '7CO0', '7KS6', '7MI6', '7PS7', '80TX',
       '82FL', '82PA', '86MI', '8CA8', '8MI4', '8OR6', '8TX7', '96WA',
       '97PN', '97TS', '98NY', '9IN3', 'AK67', 'AL18', 'AL72', 'AZ28',
       'BIKF', 'BKPR', 'CA35', 'CA39', 'CA66', 'CL36', 'CMN3', 'CNC4',
       'CO12', 'CO17', 'CO80', 'CSS3', 'CYHU', 'CYKZ', 'CYOW', 'CYTN',
       'CYUL', 'CYVR', 'CYXX', 'CYYG', 'CYYZ', 'DAAG', 'EBAW', 'EBBR',
       'EBCI', 'EBLG', 'EBMB', 'EDBA', 'EDDB', 'EDDE', 'EDDF', 'EDDH',
       'EDDK', 'EDDL', 'EDDM', 'EDDN', 'EDDP', 'EDDS', 'EDDT', 'EDDV',
       'EDDW', 'EDFD', 'EDFJ', 'EDJA', 'EDLI', 'EDLW', 'EDML', 'EDNR',
       'EDNY', 'EDOB', 'EDOS', 'EDPA', 'EDPO', 'EDXN', 'EFHK', 'EFMA',
       'EFTU', 'EGAA', 'EGBB', 'EGCC', 'EGCN', 'EGFF', 'EGGD', 'EGGP',
       'EGGW', 'EGHI', 'EGJA', 'EGKK', 'EGKL', 'EGKR', 'EGLC', 'EGLK',
       'EGLL', 'EGND', 'EGNS', 'EGNT', 'EGNX', 'EGOM', 'EGPF', 'EGPH',
       'EGSS', 'EGSU', 'EGTB', 'EGTE', 'EGTU', 'EGWU', 'EHAM', 'EHEH',
       'EHLE', 'EIBA', 'EICK', 'EIDW', 'EIKN', 'EIWT', 'EKAH', 'EKBI',
       'EKCH', 'EKKA', 'EKYT', 'ELLX', 'ENGM', 'ENSI', 'EPGD', 'EPKK',
       'EPKT', 'EPMO', 'EPPO', 'EPWA', 'EPWR', 'ESGG', 'ESKN', 'ESMS',
       'ESNS', 'ESSA', 'ESSB', 'ETMN', 'EVRA', 'EYVI', 'EYVP', 'FA80',
       'FABA', 'FALE', 'FAOR', 'FD08', 'FD20', 'FD38', 'FD81', 'FD83',
       'FL16', 'FL35', 'FL57', 'FL77', 'FL90', 'GCXO', 'GMME', 'GMMN',
       'GMTT', 'ID43', 'II40', 'II43', 'K06A', 'K06C', 'K11A', 'K1T7',
       'K20A', 'K21D', 'K29D', 'K2R1', 'K36U', 'K3F2', 'K50F', 'K61B',
       'K74S', 'K9X1', 'KABQ', 'KADS', 'KAFF', 'KAFW', 'KAGC', 'KAGR',
       'KAKH', 'KAMA', 'KAPA', 'KAUN', 'KAUS', 'KAVQ', 'KAWO', 'KAZO',
       'KBCT', 'KBDU', 'KBED', 'KBFD', 'KBFI', 'KBIF', 'KBJC', 'KBLI',
       'KBNA', 'KBOS', 'KBOW', 'KBUF', 'KBUR', 'KBVY', 'KBWI', 'KC83',
       'KCAE', 'KCCR', 'KCDW', 'KCGZ', 'KCHD', 'KCLE', 'KCLL', 'KCLT',
       'KCMA', 'KCOS', 'KCRQ', 'KCVN', 'KD83', 'KDAL', 'KDCA', 'KDEN',
       'KDFW', 'KDLL', 'KDLZ', 'KDTW', 'KDVO', 'KDVT', 'KDWH', 'KEDU',
       'KEIK', 'KELP', 'KEVB', 'KEWB', 'KEWR', 'KEZF', 'KFFZ', 'KFLD',
       'KFLG', 'KFLL', 'KFME', 'KFRG', 'KFST', 'KFTW', 'KFTY', 'KFWA',
       'KGIF', 'KGKY', 'KGNV', 'KGOO', 'KGPH', 'KGPM', 'KGRR', 'KGXY',
       'KGYR', 'KHAF', 'KHHR', 'KHIO', 'KHND', 'KHOU', 'KHPN', 'KHRL',
       'KHUA', 'KHWD', 'KHWO', 'KHYI', 'KIAD', 'KIAH', 'KIND', 'KISM',
       'KISP', 'KIWA', 'KIWS', 'KJFK', 'KJWN', 'KJWY', 'KK16', 'KKLS',
       'KL65', 'KLAR', 'KLAS', 'KLAX', 'KLBB', 'KLBL', 'KLDJ', 'KLEB',
       'KLEE', 'KLGA', 'KLGB', 'KLKU', 'KLMO', 'KLRU', 'KMAF', 'KMCC',
       'KMCF', 'KMCI', 'KMCO', 'KMDD', 'KMDW', 'KMEM', 'KMFE', 'KMGM',
       'KMHR', 'KMIA', 'KMKE', 'KMMU', 'KMSN', 'KMSP', 'KMTJ', 'KMTN',
       'KMWL', 'KMXF', 'KMYF', 'KN69', 'KN71', 'KNRN', 'KO08', 'KO69',
       'KOAK', 'KOJC', 'KOKC', 'KOMA', 'KONT', 'KOPF', 'KORD', 'KORL',
       'KOSH', 'KOTH', 'KOUN', 'KPAN', 'KPAO', 'KPBI', 'KPDX', 'KPHK',
       'KPHL', 'KPHX', 'KPIT', 'KPMD', 'KPMP', 'KPNE', 'KPRC', 'KPSP',
       'KPTK', 'KPUB', 'KPVU', 'KPWK', 'KRAL', 'KRBD', 'KRDU', 'KRFD',
       'KRFI', 'KRIR', 'KRIU', 'KRNO', 'KROC', 'KS50', 'KS97', 'KSAC',
       'KSAN', 'KSAT', 'KSBA', 'KSBP', 'KSDL', 'KSEA', 'KSFB', 'KSFO',
       'KSGR', 'KSGS', 'KSJC', 'KSLC', 'KSLR', 'KSMF', 'KSMO', 'KSNA',
       'KSRQ', 'KSTL', 'KSUS', 'KT27', 'KT67', 'KTEB', 'KTKI', 'KTMB',
       'KTME', 'KTOA', 'KTPA', 'KTTN', 'KTUS', 'KU30', 'KU42', 'KUGN',
       'KVDF', 'KVGT', 'KVNY', 'KVUO', 'KWHP', 'KWVI', 'KXNA', 'KXSA',
       'LA73', 'LBSF', 'LBWN', 'LCEN', 'LCLK', 'LEAL', 'LEBB', 'LEBL',
       'LELL', 'LEMD', 'LEMG', 'LEPA', 'LESB', 'LESO', 'LEZL', 'LFBD',
       'LFBI', 'LFBO', 'LFBP', 'LFBS', 'LFBZ', 'LFDP', 'LFLB', 'LFLJ',
       'LFLL', 'LFLY', 'LFMI', 'LFMK', 'LFML', 'LFNR', 'LFPB', 'LFPG',
       'LFPO', 'LFQQ', 'LFRN', 'LFRS', 'LFTH', 'LGAV', 'LHBP', 'LIBD',
       'LIBR', 'LICA', 'LIED', 'LILG', 'LIMA', 'LIMC', 'LIME', 'LIMF',
       'LIMJ', 'LIML', 'LIPE', 'LIPZ', 'LIRA', 'LIRF', 'LJLJ', 'LKBA',
       'LKPR', 'LKTB', 'LL22', 'LLBG', 'LLSD', 'LMML', 'LOLW', 'LOWI',
       'LOWS', 'LOWW', 'LPAR', 'LPFR', 'LPMA', 'LPPT', 'LRCK', 'LROP',
       'LS40', 'LSGG', 'LSZH', 'LSZM', 'LTAC', 'LTBA', 'LTBL', 'LTBW',
       'LTFJ', 'MD43', 'ME69', 'MMCS', 'MMMX', 'MMSD', 'MMTJ', 'MN79',
       'MS00', 'MS65', 'MY18', 'NC16', 'NK71', 'NM08', 'NM79', 'NZAA',
       'NZCH', 'NZFI', 'NZHN', 'NZNS', 'NZTG', 'NZWN', 'NZWR', 'NZWU',
       'OBBI', 'OEDF', 'OERK', 'OERY', 'OI45', 'OI49', 'OK25', 'OLBA',
       'OMAA', 'OMAL', 'OMDB', 'OMDW', 'OMSJ', 'OTBD', 'OTBH', 'OTHH',
       'PA39', 'PA49', 'PAEN', 'PAMR', 'PANC', 'RCSS', 'RCTP', 'RJBB',
       'RJFF', 'RJTK', 'RJTT', 'RPLC', 'RPLL', 'SABE', 'SADQ', 'SAEZ',
       'SAZM', 'SBBR', 'SBCO', 'SBCX', 'SBFL', 'SBGL', 'SBGR', 'SBKP',
       'SBMT', 'SBRJ', 'SBSP', 'SBVT', 'SDCO', 'SJSH', 'SKBO', 'SKGY',
       'SLCB', 'SLCY', 'SN65', 'SSJC', 'SWJX', 'TS00', 'TS35', 'UGTB',
       'UIII', 'ULLI', 'URRP', 'URWA', 'USSS', 'UT13', 'UUDD', 'UUEE',
       'UUOO', 'UUWW', 'UWUU', 'VABB', 'VAPO', 'VCBI', 'VHHH', 'VIDP',
       'VMMC', 'VOBL', 'VOMM', 'VT20', 'WI95', 'WIII', 'WIPA', 'WMKK',
       'WN21', 'WN53', 'WN80', 'XA65', 'XS14', 'YBAF', 'YBBN', 'YBCG',
       'YBLT', 'YBMC', 'YBVA', 'YCAL', 'YCVG', 'YMAV', 'YMBU', 'YMMB',
       'YMML', 'YPAD', 'YPEC', 'YPJT', 'YPPF', 'YPPH', 'YRED', 'YRSY',
       'YSCB', 'YSCH', 'YSNW', 'YSSY', 'YSTW', 'YTYH', 'YWHA', 'YWOL'],
      dtype=object)

In [117]:
flights.to_csv("flights_sample.csv", index = False)